# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "lane for Andriod Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:328159436244:android:e7c88ef4b24553309a4a41",
      firebase_cli_token: "1//09vyEUsG0FDxFCgYIARAAGAkSNwF-L9IrAgJnXHg8qwvBnHVYXdZ2H1lJg7vOveQ1SfIt-k8Lg9F3xMsDDH0FYkhRCLOkvAc7bf0",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "sinith0maas@gmail.com",
      release_notes: " Fastlane Firebase Distribution Production version"
    )
  end
end
